services:
  gateway:
    build:
      context: ./gateway
    networks: [berry]
    hostname: gateway
    depends_on: [books, reviews]
    ports:
      - "4000:4000"

  books:
    build:
      context: ./books
    networks: [berry]
    hostname: books

  reviews:
    build:
      context: ./reviews
    networks: [berry]
    hostname: reviews

networks:
  berry:
